version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://langfuse:langfuse@db:5432/langfuse
      CLICKHOUSE_MIGRATION_URL: ""
      NEXTAUTH_SECRET: your-nextauth-secret-key-change-in-production
      SALT: your-salt-key-change-in-production
      TELEMETRY_ENABLED: "false"
      NEXTAUTH_URL: http://localhost:3000
    restart: unless-stopped

volumes:
  postgres_data:
