version: '3.8'

services:
  langfuse-server:
    image: langfuse/langfuse:2.74.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      # Database connection
      DATABASE_URL: postgresql://langfuse:langfuse@db:5432/langfuse
      
      # Authentication
      NEXTAUTH_SECRET: "mysecretkey12345678901234567890"
      SALT: "mysaltkey12345678901234567890123"
      
      # Optional settings
      TELEMETRY_ENABLED: "false"
      NEXTAUTH_URL: http://localhost:3000
      
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse -d langfuse"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  langfuse_postgres_data:

networks:
  default:
    name: langfuse_network